export const FETCH_THELOAI = 'FETCH_THELOAI';
export const GET_THELOAI_ID = 'GET_THELOAI_ID';
export const THELOAI_EDIT = 'THELOAI_EDIT';
export const THELOAI_DELETE = 'THELOAI_DELETE';
export const THELOAI_SECTION = 'THELOAI_SECTION';
export const THELOAI_PUBLISH = 'THELOAI_PUBLISH';
export const THELOAI_RESET_STATE = "THELOAI_RESET_STATE"