
export const FETCH_START = "FETCH_START";
export const FETCH_END = "FETCH_END_USER"
//cungf la FETCH_END NHUNG GIA TRI CUA CAC ACTIONS PHAI KHAC NHAU NEU KO MUON FETCH DATA BI TRUNG NHAU
export const FETCH_ID_USER = "FETCH_ID_USER"
export const RESET_STATE = 'RESET_STATE'